{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "JOINING TWO CSV FILES USING INNER JOIN IN PANDAS \n",
    "\n",
    "-- We need to define index for both csv files (unique ID)\n",
    "-- The default join is left\n",
    "-- We will be joining the orders and customers file \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json \n",
    "import pandas as pd "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## to get the index, we will need to write a function \n",
    "\n",
    "def get_column_names (schemas, file_name, sorting_key = 'column_position'):             #schemas will be read as a json file while file_name is a table from the file\n",
    "    column_details = schemas[file_name]\n",
    "    columns = sorted (column_details, key = lambda col: col [sorting_key])\n",
    "    return [col ['column_name'] for col in columns]                                     #column name is from the json file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# the schema is a json file\n",
    "schemas = json.load(open('C:\\\\Users\\\\HAKEEM OLUWATOBI\\\\Research\\\\data\\\\retail_db\\\\schemas.json'))       \n",
    "\n",
    "# variable to get the column headers for orders table\n",
    "orders_columnHeader = get_column_names (schemas, 'orders')        \n",
    "\n",
    "# variable to get the column headers for customers table \n",
    "customers_columnHeader = get_column_names (schemas, 'customers')          \n",
    "\n",
    "orders_df = pd.read_csv(                        # reading the orders table into a df\n",
    "    'C:\\\\Users\\\\HAKEEM OLUWATOBI\\\\Research\\\\data\\\\retail_db\\\\orders\\\\part-00000',\n",
    "    names = orders_columnHeader\n",
    ")\n",
    "\n",
    "\n",
    "customers_df = pd.read_csv(                        # reading the customers table into a df\n",
    "    'C:\\\\Users\\\\HAKEEM OLUWATOBI\\\\Research\\\\data\\\\retail_db\\\\customers\\\\part-00000',\n",
    "    names = customers_columnHeader\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "       customer_id customer_fname customer_lname customer_email  \\\n",
      "0                1        Richard      Hernandez      XXXXXXXXX   \n",
      "1                2           Mary        Barrett      XXXXXXXXX   \n",
      "2                3            Ann          Smith      XXXXXXXXX   \n",
      "3                4           Mary          Jones      XXXXXXXXX   \n",
      "4                5         Robert         Hudson      XXXXXXXXX   \n",
      "...            ...            ...            ...            ...   \n",
      "12430        12431           Mary           Rios      XXXXXXXXX   \n",
      "12431        12432         Angela          Smith      XXXXXXXXX   \n",
      "12432        12433       Benjamin         Garcia      XXXXXXXXX   \n",
      "12433        12434           Mary          Mills      XXXXXXXXX   \n",
      "12434        12435          Laura         Horton      XXXXXXXXX   \n",
      "\n",
      "      customer_password             customer_street customer_city  \\\n",
      "0             XXXXXXXXX          6303 Heather Plaza   Brownsville   \n",
      "1             XXXXXXXXX     9526 Noble Embers Ridge     Littleton   \n",
      "2             XXXXXXXXX      3422 Blue Pioneer Bend        Caguas   \n",
      "3             XXXXXXXXX          8324 Little Common    San Marcos   \n",
      "4             XXXXXXXXX      10 Crystal River Mall         Caguas   \n",
      "...                 ...                         ...           ...   \n",
      "12430         XXXXXXXXX           1221 Cinder Pines       Kaneohe   \n",
      "12431         XXXXXXXXX  1525 Jagged Barn Highlands        Caguas   \n",
      "12432         XXXXXXXXX    5459 Noble Brook Landing     Levittown   \n",
      "12433         XXXXXXXXX        9720 Colonial Parade        Caguas   \n",
      "12434         XXXXXXXXX            5736 Honey Downs   Summerville   \n",
      "\n",
      "      customer_state  customer_zipcode  \n",
      "0                 TX             78521  \n",
      "1                 CO             80126  \n",
      "2                 PR               725  \n",
      "3                 CA             92069  \n",
      "4                 PR               725  \n",
      "...              ...               ...  \n",
      "12430             HI             96744  \n",
      "12431             PR               725  \n",
      "12432             NY             11756  \n",
      "12433             PR               725  \n",
      "12434             SC             29483  \n",
      "\n",
      "[12435 rows x 9 columns]\n"
     ]
    }
   ],
   "source": [
    "customers_df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>order_id</th>\n",
       "      <th>order_date</th>\n",
       "      <th>order_customer_id</th>\n",
       "      <th>order_status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>11599</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>256</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>12111</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>8827</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>11318</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68878</th>\n",
       "      <td>68879</td>\n",
       "      <td>2014-07-09 00:00:00.0</td>\n",
       "      <td>778</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68879</th>\n",
       "      <td>68880</td>\n",
       "      <td>2014-07-13 00:00:00.0</td>\n",
       "      <td>1117</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68880</th>\n",
       "      <td>68881</td>\n",
       "      <td>2014-07-19 00:00:00.0</td>\n",
       "      <td>2518</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68881</th>\n",
       "      <td>68882</td>\n",
       "      <td>2014-07-22 00:00:00.0</td>\n",
       "      <td>10000</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68882</th>\n",
       "      <td>68883</td>\n",
       "      <td>2014-07-23 00:00:00.0</td>\n",
       "      <td>5533</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>68883 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       order_id             order_date  order_customer_id     order_status\n",
       "0             1  2013-07-25 00:00:00.0              11599           CLOSED\n",
       "1             2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT\n",
       "2             3  2013-07-25 00:00:00.0              12111         COMPLETE\n",
       "3             4  2013-07-25 00:00:00.0               8827           CLOSED\n",
       "4             5  2013-07-25 00:00:00.0              11318         COMPLETE\n",
       "...         ...                    ...                ...              ...\n",
       "68878     68879  2014-07-09 00:00:00.0                778         COMPLETE\n",
       "68879     68880  2014-07-13 00:00:00.0               1117         COMPLETE\n",
       "68880     68881  2014-07-19 00:00:00.0               2518  PENDING_PAYMENT\n",
       "68881     68882  2014-07-22 00:00:00.0              10000          ON_HOLD\n",
       "68882     68883  2014-07-23 00:00:00.0               5533         COMPLETE\n",
       "\n",
       "[68883 rows x 4 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "orders_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## creating the index / primary key \n",
    "# order_customer_id and customer_id are the FK and PK respectively \n",
    "# we will use set_index to set the index for both columns \n",
    "\n",
    "orders_df = orders_df.set_index('order_customer_id')\n",
    "\n",
    "customers_df = customers_df.set_index('customer_id')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>customer_fname</th>\n",
       "      <th>customer_lname</th>\n",
       "      <th>customer_email</th>\n",
       "      <th>customer_password</th>\n",
       "      <th>customer_street</th>\n",
       "      <th>customer_city</th>\n",
       "      <th>customer_state</th>\n",
       "      <th>customer_zipcode</th>\n",
       "      <th>order_id</th>\n",
       "      <th>order_date</th>\n",
       "      <th>order_status</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>customer_id</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Richard</td>\n",
       "      <td>Hernandez</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>6303 Heather Plaza</td>\n",
       "      <td>Brownsville</td>\n",
       "      <td>TX</td>\n",
       "      <td>78521</td>\n",
       "      <td>22945</td>\n",
       "      <td>2013-12-13 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>15192</td>\n",
       "      <td>2013-10-29 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>33865</td>\n",
       "      <td>2014-02-18 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>57963</td>\n",
       "      <td>2013-08-02 00:00:00.0</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>67863</td>\n",
       "      <td>2013-11-30 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>42915</td>\n",
       "      <td>2014-04-16 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>51800</td>\n",
       "      <td>2014-06-14 00:00:00.0</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>61777</td>\n",
       "      <td>2013-12-26 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12435</th>\n",
       "      <td>Laura</td>\n",
       "      <td>Horton</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>5736 Honey Downs</td>\n",
       "      <td>Summerville</td>\n",
       "      <td>SC</td>\n",
       "      <td>29483</td>\n",
       "      <td>41643</td>\n",
       "      <td>2014-04-08 00:00:00.0</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12435</th>\n",
       "      <td>Laura</td>\n",
       "      <td>Horton</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>5736 Honey Downs</td>\n",
       "      <td>Summerville</td>\n",
       "      <td>SC</td>\n",
       "      <td>29483</td>\n",
       "      <td>61629</td>\n",
       "      <td>2013-12-21 00:00:00.0</td>\n",
       "      <td>CANCELED</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>68883 rows × 11 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            customer_fname customer_lname customer_email customer_password  \\\n",
       "customer_id                                                                  \n",
       "1                  Richard      Hernandez      XXXXXXXXX         XXXXXXXXX   \n",
       "2                     Mary        Barrett      XXXXXXXXX         XXXXXXXXX   \n",
       "2                     Mary        Barrett      XXXXXXXXX         XXXXXXXXX   \n",
       "2                     Mary        Barrett      XXXXXXXXX         XXXXXXXXX   \n",
       "2                     Mary        Barrett      XXXXXXXXX         XXXXXXXXX   \n",
       "...                    ...            ...            ...               ...   \n",
       "12434                 Mary          Mills      XXXXXXXXX         XXXXXXXXX   \n",
       "12434                 Mary          Mills      XXXXXXXXX         XXXXXXXXX   \n",
       "12434                 Mary          Mills      XXXXXXXXX         XXXXXXXXX   \n",
       "12435                Laura         Horton      XXXXXXXXX         XXXXXXXXX   \n",
       "12435                Laura         Horton      XXXXXXXXX         XXXXXXXXX   \n",
       "\n",
       "                     customer_street customer_city customer_state  \\\n",
       "customer_id                                                         \n",
       "1                 6303 Heather Plaza   Brownsville             TX   \n",
       "2            9526 Noble Embers Ridge     Littleton             CO   \n",
       "2            9526 Noble Embers Ridge     Littleton             CO   \n",
       "2            9526 Noble Embers Ridge     Littleton             CO   \n",
       "2            9526 Noble Embers Ridge     Littleton             CO   \n",
       "...                              ...           ...            ...   \n",
       "12434           9720 Colonial Parade        Caguas             PR   \n",
       "12434           9720 Colonial Parade        Caguas             PR   \n",
       "12434           9720 Colonial Parade        Caguas             PR   \n",
       "12435               5736 Honey Downs   Summerville             SC   \n",
       "12435               5736 Honey Downs   Summerville             SC   \n",
       "\n",
       "             customer_zipcode  order_id             order_date  \\\n",
       "customer_id                                                      \n",
       "1                       78521     22945  2013-12-13 00:00:00.0   \n",
       "2                       80126     15192  2013-10-29 00:00:00.0   \n",
       "2                       80126     33865  2014-02-18 00:00:00.0   \n",
       "2                       80126     57963  2013-08-02 00:00:00.0   \n",
       "2                       80126     67863  2013-11-30 00:00:00.0   \n",
       "...                       ...       ...                    ...   \n",
       "12434                     725     42915  2014-04-16 00:00:00.0   \n",
       "12434                     725     51800  2014-06-14 00:00:00.0   \n",
       "12434                     725     61777  2013-12-26 00:00:00.0   \n",
       "12435                   29483     41643  2014-04-08 00:00:00.0   \n",
       "12435                   29483     61629  2013-12-21 00:00:00.0   \n",
       "\n",
       "                order_status  \n",
       "customer_id                   \n",
       "1                   COMPLETE  \n",
       "2            PENDING_PAYMENT  \n",
       "2                   COMPLETE  \n",
       "2                    ON_HOLD  \n",
       "2                   COMPLETE  \n",
       "...                      ...  \n",
       "12434               COMPLETE  \n",
       "12434                ON_HOLD  \n",
       "12434               COMPLETE  \n",
       "12435                PENDING  \n",
       "12435               CANCELED  \n",
       "\n",
       "[68883 rows x 11 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Joining both tables \n",
    "\n",
    "CustomersAndOrders_df = customers_df.\\\n",
    "join(orders_df, how =  'inner')\n",
    "\n",
    "CustomersAndOrders_df               #notice its now 11 columns "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(68883, 11)"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "CustomersAndOrders_df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>customer_id</th>\n",
       "      <th>customer_fname</th>\n",
       "      <th>customer_lname</th>\n",
       "      <th>customer_email</th>\n",
       "      <th>customer_password</th>\n",
       "      <th>customer_street</th>\n",
       "      <th>customer_city</th>\n",
       "      <th>customer_state</th>\n",
       "      <th>customer_zipcode</th>\n",
       "      <th>order_id</th>\n",
       "      <th>order_date</th>\n",
       "      <th>order_status</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Richard</td>\n",
       "      <td>Hernandez</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>6303 Heather Plaza</td>\n",
       "      <td>Brownsville</td>\n",
       "      <td>TX</td>\n",
       "      <td>78521</td>\n",
       "      <td>22945</td>\n",
       "      <td>2013-12-13 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>15192</td>\n",
       "      <td>2013-10-29 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>33865</td>\n",
       "      <td>2014-02-18 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>57963</td>\n",
       "      <td>2013-08-02 00:00:00.0</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Barrett</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9526 Noble Embers Ridge</td>\n",
       "      <td>Littleton</td>\n",
       "      <td>CO</td>\n",
       "      <td>80126</td>\n",
       "      <td>67863</td>\n",
       "      <td>2013-11-30 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68878</th>\n",
       "      <td>12434</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>42915</td>\n",
       "      <td>2014-04-16 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68879</th>\n",
       "      <td>12434</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>51800</td>\n",
       "      <td>2014-06-14 00:00:00.0</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68880</th>\n",
       "      <td>12434</td>\n",
       "      <td>Mary</td>\n",
       "      <td>Mills</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>9720 Colonial Parade</td>\n",
       "      <td>Caguas</td>\n",
       "      <td>PR</td>\n",
       "      <td>725</td>\n",
       "      <td>61777</td>\n",
       "      <td>2013-12-26 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68881</th>\n",
       "      <td>12435</td>\n",
       "      <td>Laura</td>\n",
       "      <td>Horton</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>5736 Honey Downs</td>\n",
       "      <td>Summerville</td>\n",
       "      <td>SC</td>\n",
       "      <td>29483</td>\n",
       "      <td>41643</td>\n",
       "      <td>2014-04-08 00:00:00.0</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>68882</th>\n",
       "      <td>12435</td>\n",
       "      <td>Laura</td>\n",
       "      <td>Horton</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>XXXXXXXXX</td>\n",
       "      <td>5736 Honey Downs</td>\n",
       "      <td>Summerville</td>\n",
       "      <td>SC</td>\n",
       "      <td>29483</td>\n",
       "      <td>61629</td>\n",
       "      <td>2013-12-21 00:00:00.0</td>\n",
       "      <td>CANCELED</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>68883 rows × 12 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       customer_id customer_fname customer_lname customer_email  \\\n",
       "0                1        Richard      Hernandez      XXXXXXXXX   \n",
       "1                2           Mary        Barrett      XXXXXXXXX   \n",
       "2                2           Mary        Barrett      XXXXXXXXX   \n",
       "3                2           Mary        Barrett      XXXXXXXXX   \n",
       "4                2           Mary        Barrett      XXXXXXXXX   \n",
       "...            ...            ...            ...            ...   \n",
       "68878        12434           Mary          Mills      XXXXXXXXX   \n",
       "68879        12434           Mary          Mills      XXXXXXXXX   \n",
       "68880        12434           Mary          Mills      XXXXXXXXX   \n",
       "68881        12435          Laura         Horton      XXXXXXXXX   \n",
       "68882        12435          Laura         Horton      XXXXXXXXX   \n",
       "\n",
       "      customer_password          customer_street customer_city customer_state  \\\n",
       "0             XXXXXXXXX       6303 Heather Plaza   Brownsville             TX   \n",
       "1             XXXXXXXXX  9526 Noble Embers Ridge     Littleton             CO   \n",
       "2             XXXXXXXXX  9526 Noble Embers Ridge     Littleton             CO   \n",
       "3             XXXXXXXXX  9526 Noble Embers Ridge     Littleton             CO   \n",
       "4             XXXXXXXXX  9526 Noble Embers Ridge     Littleton             CO   \n",
       "...                 ...                      ...           ...            ...   \n",
       "68878         XXXXXXXXX     9720 Colonial Parade        Caguas             PR   \n",
       "68879         XXXXXXXXX     9720 Colonial Parade        Caguas             PR   \n",
       "68880         XXXXXXXXX     9720 Colonial Parade        Caguas             PR   \n",
       "68881         XXXXXXXXX         5736 Honey Downs   Summerville             SC   \n",
       "68882         XXXXXXXXX         5736 Honey Downs   Summerville             SC   \n",
       "\n",
       "       customer_zipcode  order_id             order_date     order_status  \n",
       "0                 78521     22945  2013-12-13 00:00:00.0         COMPLETE  \n",
       "1                 80126     15192  2013-10-29 00:00:00.0  PENDING_PAYMENT  \n",
       "2                 80126     33865  2014-02-18 00:00:00.0         COMPLETE  \n",
       "3                 80126     57963  2013-08-02 00:00:00.0          ON_HOLD  \n",
       "4                 80126     67863  2013-11-30 00:00:00.0         COMPLETE  \n",
       "...                 ...       ...                    ...              ...  \n",
       "68878               725     42915  2014-04-16 00:00:00.0         COMPLETE  \n",
       "68879               725     51800  2014-06-14 00:00:00.0          ON_HOLD  \n",
       "68880               725     61777  2013-12-26 00:00:00.0         COMPLETE  \n",
       "68881             29483     41643  2014-04-08 00:00:00.0          PENDING  \n",
       "68882             29483     61629  2013-12-21 00:00:00.0         CANCELED  \n",
       "\n",
       "[68883 rows x 12 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# now that we av join thge data, we need to reset index incase we want to do aggregation on the CustomersAndOrders_df\n",
    "# we will be using the reset_index function \n",
    "\n",
    "CustomersAndOrders_df. \\\n",
    "    reset_index(names = 'customer_id')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>order_count</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>customer_id</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12431</th>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12432</th>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12433</th>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12435</th>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>12405 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "             order_count\n",
       "customer_id             \n",
       "1                      1\n",
       "2                      4\n",
       "3                      7\n",
       "4                      6\n",
       "5                      4\n",
       "...                  ...\n",
       "12431                 16\n",
       "12432                 10\n",
       "12433                  4\n",
       "12434                  8\n",
       "12435                  2\n",
       "\n",
       "[12405 rows x 1 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "## now to get the count of each customer per order \n",
    "# meaning how many times a customer (customer_id) made an order \n",
    "\n",
    "CustomersAndOrders_df.\\\n",
    "    groupby('customer_id')['order_id'].\\\n",
    "    agg (order_count = 'count')               #groupby customer_id based on order_id and count "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>order_count</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>customer_id</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>221</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>569</th>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4320</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5283</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5624</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5654</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5897</th>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6316</th>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12284</th>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12431</th>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "             order_count\n",
       "customer_id             \n",
       "221                   15\n",
       "569                   16\n",
       "4320                  15\n",
       "5283                  15\n",
       "5624                  15\n",
       "5654                  15\n",
       "5897                  16\n",
       "6316                  16\n",
       "12284                 15\n",
       "12431                 16"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#to get customers that has orders grreater than 15\n",
    "\n",
    "CustomersAndOrders_df.\\\n",
    "    groupby('customer_id')['order_id'].\\\n",
    "    agg (order_count = 'count').\\\n",
    "    query('order_count >= 15')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>order_id</th>\n",
       "      <th>order_date</th>\n",
       "      <th>order_status</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>order_customer_id</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2621</th>\n",
       "      <td>57751</td>\n",
       "      <td>2014-07-24 00:00:00.0</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6463</th>\n",
       "      <td>57628</td>\n",
       "      <td>2014-07-24 00:00:00.0</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2989</th>\n",
       "      <td>57637</td>\n",
       "      <td>2014-07-24 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1211</th>\n",
       "      <td>57636</td>\n",
       "      <td>2014-07-24 00:00:00.0</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10211</th>\n",
       "      <td>57635</td>\n",
       "      <td>2014-07-24 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12294</th>\n",
       "      <td>57787</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5711</th>\n",
       "      <td>57788</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5293</th>\n",
       "      <td>57789</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2256</th>\n",
       "      <td>93</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11599</th>\n",
       "      <td>1</td>\n",
       "      <td>2013-07-25 00:00:00.0</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>68883 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                   order_id             order_date     order_status\n",
       "order_customer_id                                                  \n",
       "2621                  57751  2014-07-24 00:00:00.0           CLOSED\n",
       "6463                  57628  2014-07-24 00:00:00.0           CLOSED\n",
       "2989                  57637  2014-07-24 00:00:00.0  PENDING_PAYMENT\n",
       "1211                  57636  2014-07-24 00:00:00.0          PENDING\n",
       "10211                 57635  2014-07-24 00:00:00.0         COMPLETE\n",
       "...                     ...                    ...              ...\n",
       "12294                 57787  2013-07-25 00:00:00.0  PENDING_PAYMENT\n",
       "5711                  57788  2013-07-25 00:00:00.0         COMPLETE\n",
       "5293                  57789  2013-07-25 00:00:00.0         COMPLETE\n",
       "2256                     93  2013-07-25 00:00:00.0  PENDING_PAYMENT\n",
       "11599                     1  2013-07-25 00:00:00.0           CLOSED\n",
       "\n",
       "[68883 rows x 3 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "## sorting\n",
    "# sorting based on order_date\n",
    "\n",
    "orders_df.sort_values('order_date')                     #ascending \n",
    "orders_df.sort_values('order_date', ascending = False)           #descending "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>order_id</th>\n",
       "      <th>order_date</th>\n",
       "      <th>order_status</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>order_customer_id</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>22945</td>\n",
       "      <td>2013-12-13 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>33865</td>\n",
       "      <td>2014-02-18 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>67863</td>\n",
       "      <td>2013-11-30 00:00:00.0</td>\n",
       "      <td>COMPLETE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>15192</td>\n",
       "      <td>2013-10-29 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>57963</td>\n",
       "      <td>2013-08-02 00:00:00.0</td>\n",
       "      <td>ON_HOLD</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>5303</td>\n",
       "      <td>2013-08-26 00:00:00.0</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>4799</td>\n",
       "      <td>2013-08-23 00:00:00.0</td>\n",
       "      <td>PENDING_PAYMENT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12434</th>\n",
       "      <td>1868</td>\n",
       "      <td>2013-08-03 00:00:00.0</td>\n",
       "      <td>CLOSED</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12435</th>\n",
       "      <td>41643</td>\n",
       "      <td>2014-04-08 00:00:00.0</td>\n",
       "      <td>PENDING</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12435</th>\n",
       "      <td>61629</td>\n",
       "      <td>2013-12-21 00:00:00.0</td>\n",
       "      <td>CANCELED</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>68883 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                   order_id             order_date     order_status\n",
       "order_customer_id                                                  \n",
       "1                     22945  2013-12-13 00:00:00.0         COMPLETE\n",
       "2                     33865  2014-02-18 00:00:00.0         COMPLETE\n",
       "2                     67863  2013-11-30 00:00:00.0         COMPLETE\n",
       "2                     15192  2013-10-29 00:00:00.0  PENDING_PAYMENT\n",
       "2                     57963  2013-08-02 00:00:00.0          ON_HOLD\n",
       "...                     ...                    ...              ...\n",
       "12434                  5303  2013-08-26 00:00:00.0          PENDING\n",
       "12434                  4799  2013-08-23 00:00:00.0  PENDING_PAYMENT\n",
       "12434                  1868  2013-08-03 00:00:00.0           CLOSED\n",
       "12435                 41643  2014-04-08 00:00:00.0          PENDING\n",
       "12435                 61629  2013-12-21 00:00:00.0         CANCELED\n",
       "\n",
       "[68883 rows x 3 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "## sorting with more than one columns (composite sorting)\n",
    "## sorting order_customer_id and order_date \n",
    "\n",
    "orders_df.sort_values(['order_customer_id', 'order_date']) \n",
    "\n",
    "#using it with ascending \n",
    "orders_df.sort_values(['order_customer_id', 'order_date'], ascending=[True, False])"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
